# SPDX-FileCopyrightText: Joonas Javanainen <joonas@merulogic.com>
#
# SPDX-License-Identifier: CC0-1.0

version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
