# SPDX-FileCopyrightText: Joonas Javanainen <joonas@merulogic.com>
#
# SPDX-License-Identifier: CC0-1.0

name: ci
on:
  pull_request:
  push:
    branches:
    - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Run checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: Swatinem/rust-cache@a95ba195448af2da9b00fb742d14ffaaf3c21f43
      - name: Run checks
        run: |
          cargo check --all --all-targets --no-default-features
          cargo check --all --all-targets
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy --all

  build_and_test:
    name: Build and test
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: Swatinem/rust-cache@a95ba195448af2da9b00fb742d14ffaaf3c21f43
      - name: Build
        run: cargo build --all
      - name: Test
        run: cargo test --all
