# SPDX-FileCopyrightText: Joonas Javanainen <joonas@merulogic.com>
#
# SPDX-License-Identifier: CC0-1.0

name: ci
on:
  pull_request:
  push:
    branches:
    - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Run checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6
      - name: Run checks
        run: |
          cargo check --all --all-targets
          cargo check --all --all-targets -F defmt-03
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy --all

  build_and_test:
    name: Build and test
    needs: check
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, 1.75]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set Rust version
        run: rustup default ${{ matrix.rust }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6
      - name: Build
        run: |
          cargo build --all
          cargo build --all -F defmt-03
      - name: Build (thumbv6m-none-eabi)
        run: |
          rustup target add thumbv6m-none-eabi
          cargo build --all --target thumbv6m-none-eabi
          cargo build --all --target thumbv6m-none-eabi -F defmt-03
      - name: Build (riscv32i-unknown-none-elf)
        run: |
          rustup target add riscv32i-unknown-none-elf
          cargo build --all --target riscv32i-unknown-none-elf
          cargo build --all --target riscv32i-unknown-none-elf -F defmt-03
      - name: Test
        run: cargo test --all
